{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kgs-warehousing.serviceAccountName" . }}
  labels:
{{ include "kgs-warehousing.labels" . | nindent 4 }}
{{- end -}}
