// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehousing.Data.Database;

namespace Warehousing.Data.Migrations
{
    [DbContext(typeof(WarehousingDbContext))]
    partial class WarehousingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Warehousing.Domain.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomTariffNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<decimal>("GrossUnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("GrossValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<decimal>("NetUnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("NetValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(5);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("VatSum")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("products","dbo");
                });

            modelBuilder.Entity("Warehousing.Domain.Product.ProductHistoryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeltaQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("productHistoryLines","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
